### PR TITLE
Simplify core

### PR DESCRIPTION
**Pull request by joshrtay**
An attempt at simplifying core:

 * finished removing propTypes
 * removed sources
 * remove app
 * added DI

## DI

It occurred to me that sources was being used as a form of dependency injections in a lot of the examples in discussions. I think that if we add a DI primitive, a deku plugin / wrapper could easily reimplement sources on top of it (I'll include an example of how to do that below). 

The api for DI adds two properties to components: `statics` and `dependencies`. 

#### statics
Sets the services available to a component's children. 

#### dependencies
Injects the specified services into props.

### Example

```js
var C2 = {
  dependencies: {
    text: 'text'
  },
  render: function({props}) {
    return <div>{props.text}</div>
  }
}

var C1 = {
  statics: {
    'text': 'Goodbye World'
  },
  render: function(component){
    return <C2/>
  }
};

var App = {
  statics: {
    'text': 'Hello World'
  },
  render: function(component){
    return (
      <div>
        <C1/>
        <C2/>
      </div>
    )
  }
};

//Output: '<div><div>Goodbye World</div><div>Hello World</div></div>'
renderString(<App/>)
```

### CODE REVIEW

**Comment by anthonyshort** [comment]
This is super interesting. I was just messing around the other day with the exact same thing. What we basically end up with is `context` similar to React. I like the idea of removing propTypes, sources, and validation and just rendering elements like this.

**Comment by anthonyshort** [comment]
How are you thinking the top-level API will work with the app? Things like mounting and new node in the same container mean we need to store this so we can just do an update on `render` instead of replacing everything.

**Comment by joshrtay** [comment]
I exposed `mount` on the object returned by render. Does that suffice?

**Comment by anthonyshort** [comment]
Yeah I've been thinking about something similar to react in that you don't actually need to return anything since the whole rendering process is a side-effect anyway.

```js
import {render,element} from 'deku'

render(document.body, <App count={1} />)
render(document.body, <App count={2} />)
render(document.body, <DifferentApp />)

// maybe allow currying so you don't need to specify the container
var renderApp = render(document.body)
renderApp(<App count={1} />)
```

It doesn't really need to return anything at all and can just keep track of it internally because you can only have one container per tree.

I was thinking about how this could work with things like inspecting the tree and unmounting things:

```js
// debugging tools could use this. You could return a tree of components with their
// current state and props, then render something in devtools
var tree = inspect(document.body)

// Remove whatever tree is inside the component
remove(document.body)
```

What do you think?

**Comment by anthonyshort** [comment]
Also, the context API, which is basically what you've got there:

```js
var C1 = {
  setContext ({ props, state }) {
    return {
      text: 'Hello World'
    }
  },
  render ({ props, state }) {
    return <C2 />
  }
}

var C2 = {
  render ({ props, state, context }) {
    return <span>{context.text}</span>
  }
}
```

**Comment by joshrtay** [comment]
The high level api is interesting. How would you implement that?

There is a subtle difference between the context api and the static api I proposed. I want to make it a little more difficult to abuse context, so I propose making context a a static property of a component. It seems to me that context shouldn't change dynamically and thus doesn't need props or state to be computed. It should really be limited to being used for config, themes, and services.

**Comment by anthonyshort** [comment]
Yeah I went on a bit of a tangent there, that's just something I've been thinking about recently.

> It seems to me that context shouldn't change dynamically and thus doesn't need props or state to be computed

That's a really great point!

**Comment by joshrtay** [comment]
The nice thing about your api is that you wouldn't have to pass a renderer around to remove and mount trees. That would certainly clean up the tests.

**Comment by joshrtay** [comment]
You could also do it kind of jquery style so you don't have to export all those functions.

```js
deku(document.body).render(<App/>)
deku(docment.body).render(<DifferentApp/>)
deku(document.body).inspect()
deku(document.body).remove()
```

Not sure if that is cleaner.

**Comment by jiyinyiyong** [comment]
@joshrtay It looks better, but it's not in funtional style. I prefer writing in React's way better.

**Comment by joshrtay** [comment]
@jiyinyiyong ya... figured that'd be an issue for peeps.

so we are thinking deku will expose `render`, `inspect`, `remove` and `element` as its high level api? and that render will auto curry?

**Comment by joshrtay** [comment]
I think it would be nice to include a `use` function that makes it easy to add functionality to components. So if you wanted to create a small wrapper around deku that adds validation it would look like:

```js

import {element, render, renderString, use} from 'deku'

function validation (component) {
  if (component.propTypes) {
   var assert = validator({type: 'object', properties: component.propTypes})
   component.render = compose(component.render, function({props}) {assert(props)})
  }
}

element = use(element, validation)

export {element, render, renderString, use}

```

**Comment by anthonyshort** [comment]
> so we are thinking deku will expose render, renderString and element as its high level api? and that render will auto curry?

That would be nice. `element` should be it's own module I think. Then components don't depend on deku/the renderer at all.

```js
import {render, inspect, remove} from 'deku'
import {element} from 'virtual-element'

// curried
let body = render(document.body)
body(<div>Hello!</div>)
body(<div>Goodbye!</div>)

// Clear the container
remove(document.body)
```

I think it's important to remember that in most application code, `remove` and `inspect` won't be used. 

> should inspect and remove be exposed on render, since they are dom specific?

Probably not, I'd say that the deku module is really just a DOM renderer. I think we will keep `renderString` in the deku module for convenience (they share a lot of code), but it could pretty easily be a completely separate module.

**Comment by joshrtay** [comment]
That all makes sense to me. 

And what do you think of providing a standard way of wrapping `element` with plugins? The wrapper wouldn't have to do much except make sure that either plugins don't run more than once on a component or that the component passed to plugins is immutable.

**Comment by xdissent** [comment]
You don't really need a special plugin mechanism if `element` is in its own module, right? Just export a wrapped version and use that in your components? I could be missing something!

Huge +1 to everything so far though! Good stuff

**Comment by joshrtay** [comment]
@xdissent That works, but it's not conducive to people creating and publishing standalone plugins. It would be great, if I could do something like this in my apps.

```js
// myelement.js
var element = require('virtual-element')
var validate = require('deku-validate')
var sources = require('deku-sources')
var awesomeFeature = require('other-awesome-feature')

module.exports = use(element, validate, sources, awesomeFeature)
```

**Comment by xdissent** [comment]
I took josh's `simplify-core` branch, added anthony's proposed high level api and also updated it to use virtual-element: https://github.com/xdissent/deku/tree/virtual-element

It's not the prettiest thing, but it works. After playing with it for a while, I'm not really sure how you'd implement static/dependencies as a "plugin" or whatever (since I also removed that from core). In fact, in the `simplify-core` branch, there's a bug where re-rendering loses the static context, because the props are updated outside of `Entity()`. The main issue is that you can't get access to the entity owner from outside the render function anyway, so wrapping virtual-element won't do.

It looks like virtual-element doesn't remove undefined or null from node children, which might be a good idea to add. I ran into some issues where undefined would sneak through due to jsx, so I ended up adding some filtering in render, which isn't awesome.

I like the new api though, and it feels nice *not* having some of the magic that was in `lib/virtual.js`.

**Comment by joshrtay** [comment]
@xdissent I wasn't suggesting context / static dependencies should be implemented as a plugin. Just possibly validate and sources.

@anthonyshort Are you thinking about incorporating context in edge brach? I was thinking about it and I I like your API better for context. Although, maybe changing `setContext` to be a property rather than a method.

**Comment by anthonyshort** [comment]
I'm just going to get some of these changes merged into edge so we can get them in the next version, so I'm just keeping this PR open until we do

**Pull request closed without merging**
