### PR TITLE
Enabling plain functions as components

### PR DESCRIPTION
**Pull request by Yomguithereal**
Just a proposition to add plain function as components. I know that you might have dropped it because it seems to exist in the Quick Start section but is actually not implemented.

Related to dekujs/deku#350.

### CODE REVIEW

**Comment by kesla** [comment]
cool!

**Comment by anthonyshort** [comment]
Sounds good to me. I originally left them out just to keep it simple, but this does the job easily.

**Comment by Yomguithereal** [comment]
It's just that it is sometimes cumbersome to create an object with a render key when your component will never be more than a rendering function.

**Comment by rstacruz** [comment]
I personally don't mind not allowing functions as components. Writing your components as `{ render: () => ... }` makes it easy to 'upgrade' that component later on, plus it means there's only One True Way To Do Things™, making it simpler to grok for a new-comer.

**Comment by Yomguithereal** [comment]
The coward option is to let the option exist while not directly documenting it :smile:.

**Comment by anthonyshort** [comment]
Yeah now we need to document it :D If anyone has some free time, go for it and I'll merge it in.

**Pull request merged**
