### PR TITLE
Flattening the virtual element children array

### LINKED ISSUE #211: Allow `children` to contain arrays
It looks like recently the ability to use arrays in the virtual dom has been removed. However, it turns out to be a pretty common case, and the workaround is less than ideal.

Here are some examples off the top of my head where you want to use both objects and arrays in the body of a virtual node. Since these examples don't work, following them shows what you must do as a workaround.

_(I've run into this dozens of times the past couple weeks and had to modify the code into a complex form.)_

```html
<Tabs>
  <Tab name="Default tab"/>
  { otherTabs }
</Tabs>
```

There, the "default tab" is manually placed there, and always is there, but then you dynamically build a list of other tabs based on variables.

Here is a table example, where you have dynamic table cells, always followed by some action buttons:

```html
<Table>
  <TableBody>
    <TableRow>
      { dynamicCells }
      <TableCell>
        <Button>Standard action button</Button>
      </TableCell>
    <TableRow>
  </TableBody>
</Table>
```

Finally, here is an example where you show an alert/notice at the top of an array of sections.

```html
<Page>
  { alert }
  { sections }
</Page>
```

These are just a small sample of the cases where you mix both objects and arrays in the body of a virtual node. Because this has been removed, you first run into a confusing error message, then after you figure it out, you have to refactor to something like this:

```html
let allCells = dynamicCells;
allCells.push(
  <TableCell>
    <Button>Standard action button</Button>
  </TableCell>
);
<Table>
  <TableBody>
    <TableRow>
      { allCells }
    <TableRow>
  </TableBody>
</Table>
```

Which, that works, but it's much harder to see how the page is structured, there's a lot more searching and mental analysis required, which makes it less than simple.

Is it cool if we add this back in? The ability to use both arrays and objects in the body of a virtual dom.

cc @stevenmiller888 @anthonyshort

### PR DESCRIPTION
**Pull request by anthonyshort**
To fix #211

### CODE REVIEW

**Comment by anthonyshort** [comment]
@lancejpollard @stevenmiller888

**Comment by stevenmiller888** [comment]
Wow that was fast!

**Comment by lancejpollard** [comment]
Boom!

**Comment by anthonyshort** [comment]
Well the tests broke because I just edited it in Github haha I should probably pull this down and do it properly.

**Comment by stevenmiller888** [comment]
Lmao

**Comment by anthonyshort** [comment]
Released in `0.4.12`

**Comment by dominicbarnes** [comment]
I think this has introduced some bugs. If I use an array in one render, but then re-render w/o a collection at all, it doesn't always pick up the change.

For now, I've needed to wrap all my node arrays in some sort of parent node, but I'll try and come up with a narrowed down use-case.

**Pull request merged**
