### PR TITLE
Remove validation

### LINKED ISSUE #154: custom props validator
It would be nice to be able to use custom props validators. Would you guys be open to allowing users to override the built in validator by passing a validator function to deku. It could be something like this:

```js
var validator = require('is-my-json-valid');
app.option('validateProps', function (props, rules) {
  var validate = validator({ type: 'object', properties: rules});
  if (!validate(props)) {
   var err = validate.errors[0];
   throw new Error(err.message + ':' + err.field);
  }
});
```

### PR DESCRIPTION
**Pull request by anthonyshort**
Instead taking on extra scope and building in validation into Deku, we're going to pull it out and just require people to use some other modules that handle this already.

For example:

```js
import schema from 'validate'

let {assert} = schema({
  name: {
    type: 'string',
    required: true,
    message: 'name is required'
  }
})

let render = function({ props, state }) {
  assert(props)
  return <div></div>
}
```

This does the exact same thing as the propType validation we had before, but it's opt in and isn't built into the framework. Yay for composition.

If there's a more pure way of implementing it, I'd love to know!

Closes #154.  

@lancejpollard @dominicbarnes @stevenmiller888

### CODE REVIEW

**Comment by stevenmiller888** [comment]
+1

**Comment by anthonyshort** [comment]
Woah, I noobed up this PR. It includes everything from the `next` branch. Guess we might as well get those in too.

**Comment by anthonyshort** [comment]
The only problem with this that I can see is that `propTypes` is now only used for `sources` and nothing else.

**Comment by dominicbarnes** [comment]
+1

I would like to see sources extracted into their own thing now, rather than leaving behind `propTypes`. (it'll just become a confusing thing in the future)

Perhaps the sources should also be given their own namespace as well? (or nested under `props`?)

```js
export var sources = {
  user: 'user'
};

export function render(component) {
  // component.sources ?
  // component.props.sources ?
}
```

**Comment by dominicbarnes** [comment]
Would you guys be open to deku at least _acknowledging_ a `validate(component)` method? Rather than deku having it's own validation logic, it should at least be aware enough to run `component.validate()` if it finds one. (it seems awkward to remember to do this in `component.render()`.

```js
// using a lib
export var validate = schema({
  name: {
    type: 'string',
    required: true,
    message: 'name is required'
  }
});

// vanilla js
export function validate({ props }) {
  if (!props.name) throw new Error('name is required');
  if (typeof props.name !== 'string') throw new TypeError('name should be a string');
}
```

**Comment by lancejpollard** [comment]
+1

In terms of recognizing special functions, we should decide generally on that in a separate issue maybe? Basically, should deku support specialized hooks internally? Maybe there is a general way of doing this, or maybe we decide we want to have everything explicit. Not sure.

But +1 to the `assert(props)` stuff, makes sense!

**Comment by xdissent** [comment]
+1 Right now it feels like validateProps is just a source of uncatchable runtime errors. I will miss propTypes as a way of requiring self-documentation for components and which props they handle though. But as far as actually making prop validation errors useful, handling it yourself in render is simple and reasonable.

+1 on propTypes rename to sources or similar. I think the resolved sources should still arrive in props however - since the component is in charge of mapping the sources to local prop names, that's not surprising behaviour IMO.

Re: special function and/or backwards compatibility - It might be nice to have a way to add global hooks that fire on the before/after events, so I can set up a validation scheme for all components in my app once. Similar to React's mixins, although those come with their own can of worms (order of mixins, opting-out/in per component, overriding mixin handlers in components, cancelling events, calling "super" in overridden handlers...) Anyway, definitely a separate issue/pr.

**Comment by joshrtay** [comment]
+1 For renaming propTypes to sources and resolving sources in props.

**Comment by joshrtay** [comment]
+1 For a local validate hook. I don't really see any harm in it and I think it would allow for more readable components.

**Comment by xdissent** [comment]
@joshrtay oh totally, I was just spitballing about some easy path to backwards compatibility, so you could say like `app.hook('beforeUpdate', somePropTypesBackwardsCompatMixin)`. But you could easily do something in the component like `export let beforeUpdate = somePropTypesBackwardsCompatMixin(propTypes)` or whatever, so I'm not that worried about it. Plus it'd need access to the raw component, not the context as presented to the current hooks. Bad idea. I take it all back.

**Comment by anthonyshort** [comment]
We'll try and keep backwards compatibility for a least a couple of versions and put some deprecation warnings in there before we completely remove it, unless people are ok with removing validation in one go, it won't actually break anything, validation would just stop happening.

I'm leaning towards avoiding global hooks too, it makes things really hard to reason about. We're noticing sources is having a similar problem. You need to follow the data around to know what's happening which is imperative code smell.

I'd prefer to just allow people to create their own function that creates component objects with their  common functionality, like validation.

We've been pretty flat out at Segment recently so we haven't had time to finish off a lot of this issues, we should be able to get around to them really soon unless someone else is interested in finishing this off.

**Pull request merged**
