### PR TITLE
Add missing `arrow` in documentation

### PR DESCRIPTION
**Pull request by gillstrom**
If I'm not mistaken arrows is missing in those functions.

### CODE REVIEW

**Comment by anthonyshort** [comment]
Whoops! Thanks.

**Comment by stevenmiller888** [comment]
You don't need an arrow here

**Comment by anthonyshort** [comment]
@stevenmiller888 Only if I didn't also have a `:` there.

```
render ({ children }) {
  return <button class="my-button">{children}</button>
}
```

vs

```
render: ({ children }) => {
  return <button class="my-button">{children}</button>
}
```

**Comment by stevenmiller888** [comment]
Whoops you're right

**Comment by anthonyshort** [comment]
Pretty much why I don't use those fancy functions in object literals. It's too confusing with the 10 different ways of declaring functions.

**Pull request merged**
