### PR TITLE
Add HTML5 media events

### PR DESCRIPTION
**Pull request by askmatey**
> Various events are sent when handling media that are embedded in HTML documents using the `<audio>` and `<video>` elements;

See: https://developer.mozilla.org/de/docs/Web/Guide/Events/Media_events

Identical to React's [Media Events](https://facebook.github.io/react/docs/events.html#media-events).

```js
function render({ props, state }) {
  const {
    src
    } = props;

  const handleCanPlay => (event) => event.target.play();
  const handlePlaying => (event, component) {
    if(component.props.onPlaying) component.props.onPlaying(event);
  }

  return (
    <audio src={src} onCanPlay={handleCanPlay} onPlaying={handlePlaying}/>
  );
}
```

```js
function onHitSoundPlaying(event) {
  // K. o.!!
}

<Audio src="npc/sounds/batman_hit_pow1.ogg" onPlaying={onHitSoundPlaying}/>
```

### CODE REVIEW

**Comment by askmatey** [comment]
All timeout errors are related to Chrome on Windows NT.

**Comment by askmatey** [comment]
Triggered a Circle-CI rebuild

**Comment by anthonyshort** [comment]
I'm going to check out these failing tests later today and see what's up. If you have time to look into it, go for it. As soon as we get them passing I'll merge these two PRs and do a release. Thanks again :D

**Comment by timhudson** [comment]
https://github.com/dekujs/deku/pull/295 should fix these failing tests

**Pull request merged**
