### PR TITLE
Implement 'npm run test:jsdom'

### PR DESCRIPTION
**Pull request by rstacruz**
Not sure if you'd like this, but I thought I'd try to implement jsdom-based testing.

```
npm run test:jsdom
```

Saucelabs is taking forever! Your builds are timing out at 48mins. This makes tests in Travis run in jsdom, except when you push a new version (a tag), which invokes `test:ci`.

### CODE REVIEW

**Comment by rstacruz** [comment]
Also, your Saucelab credentials aren't available for PR's anyway.

```
Error:

Zuul tried to run tests in saucelabs, however no saucelabs credentials were provided.

See the zuul wiki (https://github.com/defunctzombie/zuul/wiki/Cloud-testing) for info on how to setup cloud testing.
```

**Comment by rstacruz** [comment]
Any word on this? would love green PR's :)

**Comment by anthonyshort** [comment]
The saucelab tests have been working up until recently. They seem to be having issues with the IE VMs. I might just disable the IE tests for now until they get it fixed up.

**Comment by anthonyshort** [comment]
Ok I managed to get them fixed. IE was getting stuck because we were using document.body on some tests. I also increased the concu

**Comment by rstacruz** [comment]
Unfortunately, Saucelabs can't be made available for pull requests.

**Pull request closed without merging**
