### PR TITLE
Add null rendering test

### PR DESCRIPTION
**Pull request by rstacruz**
Here's a failing test case.

### CODE REVIEW

**Comment by rstacruz** [comment]
okaayyy.. i could've sworn that failed on my machine...

**Comment by rstacruz** [comment]
okay, even worse: it seems CI will always pass, even if tests fail (!). Have a look at the CI logs and you should see the failure.

**Comment by rstacruz** [comment]
Relevant: https://github.com/juliangruber/tape-run/issues/27

**Comment by anthonyshort** [comment]
I'm not entirely sure if it's worth adding this feature when a user could just as easily add a `<noscript />` or `<div />` instead. What do you think?

**Comment by rstacruz** [comment]
If `undefined` is handled, then I'd expect `null` to be too. This is a very common pattern after all:

```js
return <div>
  { someCondition && <Navigation /> }
  { someCondition && <Content /> }
</div>
/* if someCondition is `null`, then we're screwed */
```

**Comment by anthonyshort** [comment]
These tests were added in another branch last week :)

**Pull request closed without merging**
