### PR TITLE
0.5.0

### LINKED ISSUE #207: Rendering null/false
If a virtual element has `null` or `false` as a child we need to maintain the state of other siblings by not unnecessarily re-rendering them just because the element next to them is now rendered as `null`. This can cause some confusion with form elements losing state.

This means the user either needs to add a `key` to the element or they need to replace the empty element manually with a `<noscript />` or similar.

The renderer should handle rendering `null` or `false` while maintaining the indexes of sibling elements when diffing so that people don't need to understand the inner workings of the diffing algorithm to avoid state loss. 

Either:
* Render `noscript` tags in place of `null` or `false`
* Make the algorithm smarter when encountering `null` or `false` by skipping them. This is much harder because we can't just map paths (eg. `0.2.4`) directly to the DOM and will require many more checks throughout different parts of the code, potentially including event handling, element removal, and anywhere else we touch the DOM based on a vnode.

React currently renders `noscript` and it works fine, so I'm going to suggest we just do that.

### PR DESCRIPTION
**Pull request by anthonyshort**
This is the first step towards #185. 

#### New Features:
* Components can be functions: `var MyButton = ({props}) => <Button>{props.text}</Button>`
* Tests now use tape and Hihat instead of Mocha
* Extracted the `dom` function out into it's own module `virtual-element`. Deku now renders generic objects. In the next version we'll remove this entirely from Deku so that components have no peer dependency on Deku.
```js
var node = {
  type: 'p',
  attributes: { class: 'Intro' },
  children: []
}
```

* Better handling of `null` and `false` child elements. Deku will render a `noscript` element so that state isn't lost between renders. Fixes #207.

#### Fixes:
* Fixed bug replacing text elements with `undefined` values
* `defaultProps` are now applied on every update, not just the initial render

#### Removed: 
* Pooling of DOM elements

#### Backwards-incompatible changes:
* Special parsing of the `class` and `style` attributes on elements. You can't pass objects or arrays to `class` and the `style` attribute won't accept an object. You should use other modules to parse these into strings. If you want to keep using the special, magic style and class attributes, you can use https://github.com/dekujs/magic-virtual-element to render virtual elements instead.
* Removed async lifecycle methods. These were experimental.

#### Next:
* Remove `virtual-element` from Deku.
* Remove sources and replace it will `context`.
* Remove `app` and render nodes directly.

### CODE REVIEW

**Comment by dominicbarnes** [comment]
Re: turning objects/arrays into className strings, do you have any particular modules you'd recommend?

**Comment by anthonyshort** [comment]
@dominicbarnes https://www.npmjs.com/package/classnames does what we were doing, but it keeps the magic out of the virtual element module. This means the module is more generic and could be used for more than just DOM trees. I think making this explicit in each component is probably better. 

We could also easily create a `virtual-element` module that still includes the magic since it's not coupled to Deku anymore. `require('magic-virtual-element)` :)

**Comment by dominicbarnes** [comment]
Cool! Yeah, I remember you mentioning that feature would be pulled out of core, I just hadn't yet found a module to replace the functionality. Thanks for the suggestion :)

**Comment by anthonyshort** [comment]
If you want to keep using the special, magic style and class attributes, you can use https://github.com/dekujs/magic-virtual-element to render virtual elements instead.

**Comment by anthonyshort** [comment]
If we export `magic-virtual-element` as `dom` for now and show a deprecation warning in dev, then this release should be mostly backwards compatible.

**Pull request merged**
